- hosts: all
  become: yes
  tasks:
    - name: Create the 'rabin' user
      user:
        name: rabin
        append: yes
        state: present
        create_home: yes
        shell: /bin/bash

    - name: Allow 'rabin' to have passwordless sudo
      lineinfile:
        dest: /etc/sudoers
        line: 'rabin ALL=(ALL) NOPASSWD: ALL'
        validate: 'visudo -cf %s'

    - name: Ensure the .ssh directory exists for the rabin user
      file:
        path: /home/rabin/.ssh
        state: directory
        mode: '0700'
        owner: rabin
        group: rabin

    - name: Copy the public key from Ansible server to the rabin user's authorized_keys
      authorized_key:
        user: rabin
        state: present
        key: "{{ lookup('file', '/home/ubuntu/.ssh/id_rsa.pub') }}"

    - name: Ensure correct permissions on the authorized_keys file biku
      file:
        path: /home/rabin/.ssh/authorized_keys
        mode: '0600'
        owner: rabin
        group: rabin

