- hosts: master
  become: yes
  tasks:
    - name: Initialize the Kubernetes cluster
      shell: kubeadm init --pod-network-cidr=10.244.0.0/16 >> cluster_initialized.txt
      args:
        chdir: $HOME
        creates: cluster_initialized.txt

    - name: Create .kube directory for kubeconfig
      file:
        path: /home/rabin/.kube
        state: directory
        mode: '0755'
        owner: rabin
        group: rabin

    - name: Copy admin.conf to user's kube config
      copy:
        src: /etc/kubernetes/admin.conf
        dest: /home/rabin/.kube/config
        remote_src: yes
        owner: rabin
        group: rabin
        mode: '0644'

    - name: Ensure kubeconfig is exported in environment
      shell: export KUBECONFIG=/home/rabin/.kube/config
      environment:
        KUBECONFIG: /home/rabin/.kube/config

    - name: Wait for Kubernetes API server to be ready
      shell: kubectl get nodes
      register: result
      until: result.rc == 0
      retries: 10
      delay: 15
      environment:
        KUBECONFIG: /home/rabin/.kube/config

    - name: Install Pod network (Flannel)
      shell: kubectl apply -f https://raw.githubusercontent.com/flannel-io/flannel/master/Documentation/kube-flannel.yml --validate=false >> pod_network_setup.txt
      args:
        chdir: $HOME
        creates: pod_network_setup.txt
      environment:
        KUBECONFIG: /home/rabin/.kube/config

    - name: Get the token for joining the worker nodes
      shell: kubeadm token create --print-join-command
      register: kubernetes_join_command

    - name: Display the join command
      debug:
        msg: "{{ kubernetes_join_command.stdout }}"

    - name: Copy join command to local file
      become: yes
      local_action:
        module: copy
        content: "{{ kubernetes_join_command.stdout_lines[0] }}"
        dest: /tmp/kubernetes_join_command
        mode: '0777'
